require("nizardev.plugins-setup")

require("nizardev.core.options")
require("nizardev.core.keymaps")
require("nizardev.core.colorschema")

require("nizardev.plugins.comment")
require("nizardev.plugins.nvim-tree")
require("nizardev.plugins.lualine")
require("nizardev.plugins.telescope")
require("nizardev.plugins.nvim-cmp")
require("nizardev.plugins.lsp.mason")
require("nizardev.plugins.lsp.lspsaga")
require("nizardev.plugins.lsp.lspconfig")
require("nizardev.plugins.lsp.null-ls")
require("nizardev.plugins.autopairs")
require("nizardev.plugins.treesitter")
require("nizardev.plugins.gitsigns")
